wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.17.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720961112
    t:
      1:
      - 5
      - 6
      - 35
      - 53
      - 55
      - 69
      - 105
      2:
      - 5
      - 6
      - 35
      - 53
      - 55
      - 69
      - 105
      3:
      - 2
      - 13
      - 23
      4: 3.9.13
      5: 0.17.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
