wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.10
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720879509.341105
    t:
      1:
      - 1
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      - 69
      - 105
      2:
      - 1
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      - 69
      - 105
      3:
      - 2
      - 13
      - 15
      - 23
      4: 3.11.3
      5: 0.15.10
      8:
      - 1
      - 3
      - 5
