wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720887168
    t:
      1:
      - 5
      - 6
      - 35
      - 53
      - 55
      - 69
      2:
      - 5
      - 6
      - 35
      - 53
      - 55
      - 69
      3:
      - 2
      - 13
      - 15
      - 23
      4: 3.10.13
      5: 0.17.4
      8:
      - 1
      - 5
      13: linux-x86_64
